### ISSUE TITLE
请教：怎样实现header处的categories功能？

### ISSUE THREAD

**Issue by mkt1733** [Steven-Zhl/Future-Imperfect_Jekyll-Template#1]
首先感谢大佬做了这么厉害的template出来，我原来找到的template是[这位毛子大哥的](https://github.com/kaptn3/future-imperfect/)，他的header有categories的分类选项，想问问大佬的template有实现这个吗？谢谢！

**Comment by Steven-Zhl** [comment]
## 功能
* 有类似的功能。在header中有个“归档”页面，其中有两个筛选框(或者说下拉菜单)，可以同时按照category和tag来筛选文章。
## 关于实现
* 至于实现，主要靠的是这部分[JS脚本](https://github.com/Steven-Zhl/Future-Imperfect_Jekyll-Template/blob/main/_includes/archive-script.html)。
  * 第一部分是`selectChange`函数，它根据筛选框中的选项，隐藏掉不符合选项的文章，显示符合选项的文章，这通过调整`style`属性中的`display`实现。
  * 第二部分检测url中的参数，如果携带了关于category或tag的参数，则会将参数值赋给筛选框，然后调用一下`selectChange()`。
* 此外这两个筛选框的`onchange`触发器也绑定了`selectChange()`，这样每次更改选项后都会执行一次，响应了用户的操作。

**Comment by Steven-Zhl** [comment]
这个实现起来挺简单的，用liquid模板遍历category就行。我下次更新的时候加上，大概周末之前就能做出来。

**Comment by Steven-Zhl** [comment]
现在已经基本完成了，在`_config.yml`中有这么一段：
```yaml
# 顶栏样式配置/Header style settings
header:
  menu: false # 是否在顶栏显示“菜单”/Whether to display "menu" in the header.
  about: false # 是否在顶栏显示“关于”/Whether to display "About" in the header.
  archive: false # 是否在顶栏显示“归档”/Whether to display "Archive" in the header.
  list-categories: true # 是否在顶栏直接列出全部分类/Whether to list all categories directly in the header.
```
按照上面的写法，效果如下：
![image](https://github.com/Steven-Zhl/Future-Imperfect_Jekyll-Template/assets/80385790/dddfc15a-a9e7-41aa-8157-730862ae4026)
打开任意一个后，效果如下：
![image](https://github.com/Steven-Zhl/Future-Imperfect_Jekyll-Template/assets/80385790/879d7887-1e50-4c7e-bede-a7f1132133db)
这样可以吗？
